name: "Ren'Py Build"
author: "NyanCatda"
description: "Build Ren'Py project"
inputs:
  sdk_version:
    description: "Ren'Py SDK version"
    default: "8.1.3"
    required: true
  project_path:
    description: "Project folder path"
    default: "."
  target_platform:
    description: "Build target platform"
    required: false
    type: choice
    options:
      - win
      - linux
      - mac
      - android
      - market
      - web
outputs:
  artifact_path:
    description: "Path to the built artifact"
  version:
    description: "Project version"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.sdk_version }}
    - ${{ inputs.project_path }}
    - ${{ inputs.target_platform }}
branding:
  color: "red"
  icon: "package"
